export const sidebarOptionsEnum = {
    "company": "company",
    "zones": "zones",
    "zones/singlezonedetails": "zones",
    "zones/showdevices": "zones",
    "zones/authmodal": "zones",
    "zones/updatezone": "zones",
    "zones/create-device": "zones",
    "zones/update-device": "zones",
    "events": "events",
    "events/normal-events": "events",
    "events/onu-events": "events",
    "events/incomming-envent-detail": "events",
    "events/validation-envent-detail": "events",
    "all-employees": "employees",
    "all-employees/employee-Detail": "employees",
    "all-employees/add-employee": "employees",
    "all-employees/update-employee": "employees",
    "all-employees/uploademployeefile": "employees",
    "all-employees/employee-docs": "employees",
    "all-employees/employee-docs-complete": "employees",
    "allvehicles": "vehicles",
    "allvehicles/create-vehicle": "vehicles", 
    "allvehicles/vehicle-detail": "vehicles",
    "allvehicles/update-vehicle": "vehicles",
    "contractors": "contractor",
    "contractors/create-contract": "contractor", 
    "contractors/add-contractor": "contractor",
    "contractors/update-contractor": "contractor",
    "contractors/employee-contractor-details": "contractor",
    "contractors/contractor-approve-document": "contractor",
    "contractors/upload-contractor": "contractor",
    "contractors/contractor-details": "contractor",
    "contractors/contractor-detail": "contractor",
    "contractors/vehicle-detail": "contractor",
    "contractors/vehicleDetail": "contractor",
    "contractors/update-contract": "contractor",
    "contractors/employeeDetail": "contractor",
    "suppliers": "provider",
    "suppliers/create-order": "provider",
    "suppliers/upload-contractor": "provider",
    "suppliers/order-details": "provider",
    "suppliers/vehicle-detail": "provider",
    "suppliers/add-suppliers": "provider",
    "suppliers/update-suppliers": "provider", 
    "suppliers/employee-suppliers-details": "provider",
    "suppliers/approve-documents": "provider", 
    "suppliers/upload-supplier": "provider", 
    "suppliers/suppliers_deatail_page": "provider",
    "payroll": "payroll",
    "payroll/manage-attendence": "payroll",
    "payroll/email-setting": "emailSetting",
    "backup": "backup",
    //   {/* @hospitality */}
    //           <Route path="hospitality" element={<Hospitality />} />
    //           <Route path="hospitality" element={<HospitalityOutlet />}>
    //             <Route path="add-room" element={<AddUpdateHospitality />} />
    //             <Route path="room-detail" element={<RoomDetail />} />

    //           </Route>
    "departments": "departments",
    "company/workshift-panel": "workshift",
    "company/roles-panel": "previlageSetting",
    "company/onboarding": "onBoarding",
    "company/user-doc-panel": "userDocument",
    "company/vehicle-doc-panel": "vehicleDocument",
    "devices": "devices",
    "announcement-panel": "announcements",
    "profile": "profile"


}