/* Auth Actions Types*/
export const LOGIN_REQUEST_ACTION = "LOGIN_REQUEST_ACTION";
export const LOGIN_CONFIRMED_ACTION = "LOGIN_CONFIRMED_ACTION";
export const LOGIN_FAILED_ACTION = "LOGIN_FAILED_ACTION";
export const LOG_OUT_ACTION = "LOG_OUT_ACTION";

// company Actions Types
export const UPDATE_COMPANY_DATA = "UPDATE_COMPANY_DATA";
export const GET_COMPANY_DATA = "GET_COMPANY_DATA";

export const CREATE_NEW_EMPLOYEE = "CREATE_NEW_EMPLOYEE";

