export const MODELS = {
  Notification: 4,
  EmployeeCompanyDocument: 10,
  SupplierCompanyDocument: 11,
  SupplierVehicleCompanyDocument: 12,
  WorkShift: 13,
  Role: 14,
  Zone: 16,
  Device: 17,
  Onboarding: 21,
  User: 25,
  vehicle: 26,
  UserAccessLog: 27,
  VehicleAccessLog: 28,
  ContractorCompanyDocument: 29,
  ContractorVehicleCompanyDocument: 30,
  Department: 31,
  Contract: 32,
  Order: 33,
  Employee: 9,
  Contractor: 6,
  Supplier: 7
};